### ISSUE TITLE
bug in dev mode: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java#404]
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.IllegalArgumentException: java.util.concurrent.CompletionException: io.sphere.sdk.json.JsonException: detailMessage: com.fasterxml.jackson.databind.JsonMappingException: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding@1655879e (through reference chain: io.sphere.sdk.payments.PaymentDraftImpl["amountPlanned"])
http response: <unknown>
SDK: 1.0.0
project: <unknown>
Java: 1.8.0_45
cwd: /Users/mschleichardt/dev/commercetools-sunrise-java
sphere request: <unknown>
additional notes: []
Javadoc: http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/json/JsonException.html
]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.java8.FuturesConvertersImpl$P.accept(FutureConvertersImpl.scala:94)
	at scala.concurrent.java8.FuturesConvertersImpl$P.accept(FutureConvertersImpl.scala:89)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:739)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: java.util.concurrent.CompletionException: io.sphere.sdk.json.JsonException: detailMessage: com.fasterxml.jackson.databind.JsonMappingException: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding@1655879e (through reference chain: io.sphere.sdk.payments.PaymentDraftImpl["amountPlanned"])
http response: <unknown>
SDK: 1.0.0
project: <unknown>
Java: 1.8.0_45
cwd: /Users/mschleichardt/dev/commercetools-sunrise-java
sphere request: <unknown>
additional notes: []
Javadoc: http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/json/JsonException.html

	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1969)
	at io.sphere.sdk.utils.FutureUtils.lambda$null$26(FutureUtils.java:53)
	at io.sphere.sdk.utils.FutureUtils$$Lambda$485/235567319.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2132)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:110)
	at io.sphere.sdk.utils.FutureUtils.lambda$recoverWithAsync$27(FutureUtils.java:49)
	at io.sphere.sdk.utils.FutureUtils$$Lambda$458/907593446.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	... 8 common frames omitted
Caused by: java.lang.IllegalArgumentException: java.util.concurrent.CompletionException: io.sphere.sdk.json.JsonException: detailMessage: com.fasterxml.jackson.databind.JsonMappingException: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding@1655879e (through reference chain: io.sphere.sdk.payments.PaymentDraftImpl["amountPlanned"])
http response: <unknown>
SDK: 1.0.0
project: <unknown>
Java: 1.8.0_45
cwd: /Users/mschleichardt/dev/commercetools-sunrise-java
sphere request: <unknown>
additional notes: []
Javadoc: http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/json/JsonException.html

	at shoppingcart.checkout.payment.CheckoutPaymentPageController.handleSetPaymentToCartError(CheckoutPaymentPageController.java:194)
	at shoppingcart.checkout.payment.CheckoutPaymentPageController.lambda$null$2(CheckoutPaymentPageController.java:100)
	at shoppingcart.checkout.payment.CheckoutPaymentPageController$$Lambda$455/728064183.apply(Unknown Source)
	at io.sphere.sdk.utils.FutureUtils.lambda$recoverWithAsync$27(FutureUtils.java:48)
	... 11 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.sphere.sdk.json.JsonException: detailMessage: com.fasterxml.jackson.databind.JsonMappingException: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding@1655879e (through reference chain: io.sphere.sdk.payments.PaymentDraftImpl["amountPlanned"])
http response: <unknown>
SDK: 1.0.0
project: <unknown>
Java: 1.8.0_45
cwd: /Users/mschleichardt/dev/commercetools-sunrise-java
sphere request: <unknown>
additional notes: []
Javadoc: http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/json/JsonException.html

	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.sphere.sdk.json.JsonException: detailMessage: com.fasterxml.jackson.databind.JsonMappingException: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding@1655879e (through reference chain: io.sphere.sdk.payments.PaymentDraftImpl["amountPlanned"])
http response: <unknown>
SDK: 1.0.0
project: <unknown>
Java: 1.8.0_45
cwd: /Users/mschleichardt/dev/commercetools-sunrise-java
sphere request: <unknown>
additional notes: []
Javadoc: http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/json/JsonException.html

	at io.sphere.sdk.json.SphereJsonUtils.executing(SphereJsonUtils.java:285)
	at io.sphere.sdk.json.SphereJsonUtils.toJsonString(SphereJsonUtils.java:60)
	at io.sphere.sdk.commands.MetaModelCreateCommandImpl.httpBody(MetaModelCreateCommandImpl.java:72)
	at io.sphere.sdk.commands.MetaModelCreateCommandImpl.httpRequestIntent(MetaModelCreateCommandImpl.java:58)
	at io.sphere.sdk.client.SphereClientImpl.createHttpRequest(SphereClientImpl.java:85)
	at io.sphere.sdk.client.SphereClientImpl.execute(SphereClientImpl.java:46)
	at io.sphere.sdk.client.SphereClientImpl.lambda$execute$0(SphereClientImpl.java:39)
	at io.sphere.sdk.client.SphereClientImpl$$Lambda$69/513305337.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 6 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding@1655879e (through reference chain: io.sphere.sdk.payments.PaymentDraftImpl["amountPlanned"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:199)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:686)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3525)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2915)
	at io.sphere.sdk.json.SphereJsonUtils.lambda$toJsonString$0(SphereJsonUtils.java:60)
	at io.sphere.sdk.json.SphereJsonUtils$$Lambda$339/1794627106.get(Unknown Source)
	at io.sphere.sdk.json.SphereJsonUtils.executing(SphereJsonUtils.java:283)
	... 14 common frames omitted
Caused by: javax.money.MonetaryException: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding@1655879e
	at org.javamoney.moneta.FastMoney.with(FastMoney.java:687)
	at org.javamoney.moneta.FastMoney.with(FastMoney.java:83)
	at io.sphere.sdk.utils.MoneyImpl.with(MoneyImpl.java:31)
	at io.sphere.sdk.json.MoneyRepresentation.amountToCents(MoneyRepresentation.java:51)
	at io.sphere.sdk.json.MoneyRepresentation.<init>(MoneyRepresentation.java:29)
	at io.sphere.sdk.json.MoneySerializer.serialize(MoneySerializer.java:20)
	at io.sphere.sdk.json.MoneySerializer.serialize(MoneySerializer.java:11)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:656)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	... 21 common frames omitted
Caused by: javax.money.MonetaryException: No rounding provided for CurrencyUnit: EUR
	at javax.money.spi.MonetaryRoundingsSingletonSpi.lambda$getRounding$29(MonetaryRoundingsSingletonSpi.java:92)
	at javax.money.spi.MonetaryRoundingsSingletonSpi$$Lambda$407/1165655388.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at javax.money.spi.MonetaryRoundingsSingletonSpi.getRounding(MonetaryRoundingsSingletonSpi.java:91)
	at javax.money.Monetary.getRounding(Monetary.java:187)
	at javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding.apply(DefaultMonetaryRoundingsSingletonSpi.java:168)
	at org.javamoney.moneta.FastMoney.with(FastMoney.java:683)
	... 29 common frames omitted
```

no problem in heroku or executing the binary created by `sbt stage`

**Comment by schleichardt** [comment]
I think it has something to do with the class loading and without sbt restart and clean the same behaviour happened again no matter the change.

The workaround to fix this issue is to execute

```java
Monetary.getDefaultRounding().apply(MoneyImpl.ofCents(123, "EUR"));
```

when the web application starts.

**Comment by schleichardt** [comment]
current fix code:

```java
    private void applyJavaMoneyHack() {
        //fixes https://github.com/commercetools/commercetools-sunrise-java/issues/404
        //exception play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.IllegalArgumentException: java.util.concurrent.CompletionException: io.sphere.sdk.json.JsonException: detailMessage: com.fasterxml.jackson.databind.JsonMappingException: Operator failed: javax.money.DefaultMonetaryRoundingsSingletonSpi$DefaultCurrencyRounding@1655879e (through reference chain: io.sphere.sdk.payments.PaymentDraftImpl["amountPlanned"])
        Monetary.getDefaultRounding();
        Monetary.getDefaultRounding().apply(MoneyImpl.ofCents(123, "EUR"));
        Monetary.getDefaultAmountType();
        MonetaryFormats.getDefaultFormatProviderChain();
        Monetary.getDefaultCurrencyProviderChain();
    }
```
