### ISSUE TITLE
Typo in Release Notes? -> Module [demo.common.ComponentsModule] cannot be instantiated

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-sunrise-java#446]
[The release notes of 0.8.0](https://github.com/commercetools/commercetools-sunrise-java/releases/tag/v0.8.0) say

> - fix a JavaMoney related bug, please put this at the top of the play.modules.enabled in application.conf
> ``
> ```
> play.modules.enabled += "com.commercetools.sunrise.common.contexts.RequestScopeModule"
> play.modules.enabled += "demo.common.ComponentsModule"
> ```
> 
> (you may need to delete a duplicate entry for play.modules.enabled += "demo.common.ComponentsModule")

I cannot find `demo.common.ComponentsModule` and Play! can't, either:
```
play.api.PlayException: Cannot load module[Module [demo.common.ComponentsModule] cannot be instantiated.]
	at play.api.inject.Modules$.play$api$inject$Modules$$constructModule(Module.scala:147)
	at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:114)
	at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:113)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
Caused by: java.lang.ClassNotFoundException: demo.common.ComponentsModule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.api.inject.Modules$$anonfun$locate$1$$anonfun$apply$1.apply(Module.scala:115)
	at play.api.inject.Modules$$anonfun$locate$1$$anonfun$apply$1.apply(Module.scala:115)
	at play.api.inject.Modules$.play$api$inject$Modules$$constructModule(Module.scala:121)
	at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:114)
	at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:113)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
```

It's also not part of [commercetools-sunrise-java-demo](https://github.com/commercetools/commercetools-sunrise-java-demo). Should we just ignore it?

BTW: Thanks for releasing to Maven Central!

**Comment by schleichardt** [comment]
Ups, ComponentsModule it is not part of the framework but of the demo in the 'old' repository. There is some code to fix a JavaMoney issue:  https://github.com/commercetools/commercetools-sunrise-java/blob/master/app/demo/common/ComponentsModule.java#L23

so 

```
play.modules.enabled += "demo.common.ComponentsModule"
```

and the JavaMoney bug text should be removed from the release notes.
@lauraluiz ok?

@lauraluiz maybe we can put the money fix in the request scope module so it is enabled by default and mention it in 0.9.0

**Comment by lauraluiz** [comment]
@schleichardt yes please fix the release notes and maybe put the explanation in the "Demo" section instead (because demo is affected by it), maybe you can point to this issue so that developers can still fix it if they find it.

We should definitely add it in future releases. I just hope we find a most permanent solution for it though ;)
