### ISSUE TITLE
NPE in CategoryTreeInNewProvider.java:37 in production mode

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-sunrise-java#447]
I'm not entirely sure whether this issue belongs here or to [commercetools-sunrise-java-demo](https://github.com/commercetools/commercetools-sunrise-java-demo), I'm reporting it here because this repository hosts the class that throws the exception.

We're internally building a project that we recently based on [commercetools-sunrise-java-demo](https://github.com/commercetools/commercetools-sunrise-java-demo). This worked fine when we based our work on Version 0.7.0-x5-SNAPSHOT of the Sunrise framework. Both dev mode and prod mode were working.

When I switched to 0.7.0, running our shop works fine in dev mode (i.e. with `sbt run`, `sbt test` and `sbt it:test`), but when I start in prod mode (i.e. `./sbt clean stage && target/universal/stage/bin/frontend -Dplay.crypto.secret=12345`) I get the following errors (when the application starts, before it starts accepting connections; the problem persists with framework version 0.8.0).

```
[warn] c.g.j.h.HelperRegistry - Helper 'i18n' has been replaced by 'HandlebarsI18nHelper[i18n=<null>]'
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  while locating com.commercetools.sunrise.common.categorytree.CategoryTreeInNewProvider
  at com.commercetools.sunrise.common.categorytree.CategoryTreeModule.configure(CategoryTreeModule.java:14) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.categorytree.CategoryTreeModule)
  while locating io.sphere.sdk.categories.CategoryTree annotated with @com.google.inject.name.Named(value=new)
Caused by: java.lang.NullPointerException
	at com.commercetools.sunrise.common.categorytree.CategoryTreeInNewProvider.lambda$getCategoryNew$0(CategoryTreeInNewProvider.java:37)
	at java.util.Optional.flatMap(Optional.java:241)
	at com.commercetools.sunrise.common.categorytree.CategoryTreeInNewProvider.getCategoryNew(CategoryTreeInNewProvider.java:37)
	at com.commercetools.sunrise.common.categorytree.CategoryTreeInNewProvider.get(CategoryTreeInNewProvider.java:27)
	at com.commercetools.sunrise.common.categorytree.CategoryTreeInNewProvider.get(CategoryTreeInNewProvider.java:15)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
	at play.inject.guice.GuiceBuilder.injector(GuiceBuilder.java:208)
	at play.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.java:127)
	at play.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.java:34)
	at play.api.ApplicationLoader$JavaApplicationLoaderAdapter$1.load(ApplicationLoader.scala:67)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)

2) Error in custom provider, com.commercetools.sunrise.common.SunriseInitializationException: Could not fetch categories
  while locating com.commercetools.sunrise.common.categorytree.CategoryTreeProvider
  at com.commercetools.sunrise.common.categorytree.CategoryTreeModule.configure(CategoryTreeModule.java:13) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.categorytree.CategoryTreeModule)
  while locating io.sphere.sdk.categories.CategoryTree
Caused by: com.commercetools.sunrise.common.SunriseInitializationException: Could not fetch categories
	at com.commercetools.sunrise.common.categorytree.CategoryTreeProvider.get(CategoryTreeProvider.java:25)
	at com.commercetools.sunrise.common.categorytree.CategoryTreeProvider.get(CategoryTreeProvider.java:12)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
```

and so on ...

Lines 35-38 of CategoryInNewProvider.java are

```
    private Optional<Category> getCategoryNew() {
        return Optional.ofNullable(configuration.getString(CONFIG_CATEGORY_NEW_EXT_ID))
                .flatMap(extId -> categoryTree.findByExternalId(extId));
    }
```

I debugged the code: categoryTree is `null`.

Did you experience that issue? Do you have any hints at what might have caused it? We could provide further details if required.

**Comment by lauraluiz** [comment]
@selo-ecube actually the "so on" part is the most interesting ;)
So far it is complaining that the new category tree could not be created, because the category tree could not be fetched. Now we need to know why the category tree could not be created. It could be because it cannot connect with Commercetools Platform at the end.

**Comment by selo-ecube** [comment]
Thanks for the hint! I was able to fix the problem. When trying to reproduce the problem locally, I forgot the -Dconfig.resource=prod.conf when starting Play! in prod mode, i.e. the Commercetools credentials were missing.

**Comment by lauraluiz** [comment]
Good! Unfortunately the error for the credentials gets lost with the verbose output of Guice, we have to work on that.

**Comment by schleichardt** [comment]
in demo we added in application.conf

```
play.http.errorHandler = "com.commercetools.sunrise.http.SunriseDefaultHttpErrorHandler"
```

so it warns better if the credentials are missing

**Comment by selo-ecube** [comment]
We're using that error handler, too. But the exception happened while the application was loading, before it started serving requests.

I'm not that familiar with Guice, but maybe it's possible to use a custom injector that ensures that the Commercetools credentials are available.
