### ISSUE TITLE
Add RequestScopedModule to v.0.8.0 release notes again?

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-sunrise-java#462]
Maybe you could add the hint on the

```
play.modules.enabled += "com.commercetools.sunrise.common.contexts.RequestScopeModule"
```

line in application.conf to the [v.0.8.0 release notes](https://github.com/commercetools/commercetools-sunrise-java/releases/tag/v0.8.0) again that was removed during #446 .

A colleague of mine got the following exception without the module.

```
[error] application - 

! @70p18i8ge - Internal server error, for (GET) [/] ->
 
play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.contexts.ContextDataModule.configure(ContextDataModule.java:17) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.contexts.ContextDataModule)

2) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.contexts.ContextDataModule.configure(ContextDataModule.java:18) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.contexts.ContextDataModule)

3) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.contexts.ContextDataModule.configure(ContextDataModule.java:19) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.contexts.ContextDataModule)

4) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.contexts.ContextDataModule.configure(ContextDataModule.java:21) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.contexts.ContextDataModule)

5) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.ctp.CtpModule.configure(CtpModule.java:25) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.ctp.CtpModule)

5 errors]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:170)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:126)
	at scala.Option.map(Option.scala:146)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:126)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:124)
	at scala.util.Success.flatMap(Try.scala:231)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:124)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.contexts.ContextDataModule.configure(ContextDataModule.java:17) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.contexts.ContextDataModule)

2) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.contexts.ContextDataModule.configure(ContextDataModule.java:18) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.contexts.ContextDataModule)

3) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.contexts.ContextDataModule.configure(ContextDataModule.java:19) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.contexts.ContextDataModule)

4) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.contexts.ContextDataModule.configure(ContextDataModule.java:21) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.contexts.ContextDataModule)

5) No scope is bound to com.commercetools.sunrise.common.contexts.RequestScoped.
  at com.commercetools.sunrise.common.ctp.CtpModule.configure(CtpModule.java:25) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.ctp.CtpModule)

5 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
	at play.inject.guice.GuiceBuilder.injector(GuiceBuilder.java:208)
	at play.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.java:127)
	at play.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.java:34)
	at play.api.ApplicationLoader$JavaApplicationLoaderAdapter$1.load(ApplicationLoader.scala:67)
[error] o.a.DefaultAsyncHttpClient - AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks
```

**Comment by lauraluiz** [comment]
@selo-ecube good catch. I removed everything because I thought it was only referring to the Money issue, now I see it also contained the other `RequestScopedModule`.

I have updated the release notes so that it contains this line of code with the proper explanation.

Thanks a lot and sorry for the mistake!
